substitutions:
  name: shelly1
  friendly_name: Shelly 1 Smart Relay
  name_add_mac_suffix: "true"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: ${name_add_mac_suffix}
  project:
    name: matiasjrossi.shelly1
    version: "1.0"

dashboard_import:
  package_import_url: github://matiasjrossi/esphome-devices/shelly1.yaml

<<: !include common.yaml

esp8266:
  board: esp01_1m

logger:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: Button
    on_state:
      then:
        - switch.toggle: relay

sensor:
  - platform: wifi_signal
    name: WiFi Signal

switch:
  - platform: gpio
    name: None
    id: relay
    pin: GPIO4
    restore_mode: RESTORE_DEFAULT_OFF
